# Generated by Django 6.0.6 on 2026-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0002_managertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertoken',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
