# Generated by Django 6.0.6 on 2026-10-06 09:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0003_alter_managertoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='project_name',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cylinder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('project_name'), django.db.models.functions.text.Lower('serial_number'), name='unique_serial_per_project'),
        ),
    ]
